/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: android-x86"
#define DATE "built on: Fri Jan 17 11:09:15 2020 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','c','l','a','n','g',' ',
    '-','f','P','I','C',' ','-','p','t','h','r','e','a','d',' ',' ',
    '-','t','a','r','g','e','t',' ','i','6','8','6','-','l','i','n',
    'u','x','-','a','n','d','r','o','i','d',' ','-','g','c','c','-',
    't','o','o','l','c','h','a','i','n',' ','/','o','p','t','/','a',
    'n','d','r','o','i','d','-','n','d','k','-','r','2','0','b','/',
    't','o','o','l','c','h','a','i','n','s','/','x','8','6','-','4',
    '.','9','/','p','r','e','b','u','i','l','t','/','l','i','n','u',
    'x','-','x','8','6','_','6','4',' ','-','-','s','y','s','r','o',
    'o','t','=','/','o','p','t','/','a','n','d','r','o','i','d','-',
    'n','d','k','-','r','2','0','b','/','p','l','a','t','f','o','r',
    'm','s','/','a','n','d','r','o','i','d','-','2','1','/','a','r',
    'c','h','-','x','8','6',' ','-','W','a','l','l',' ','-','O','3',
    ' ','-','f','o','m','i','t','-','f','r','a','m','e','-','p','o',
    'i','n','t','e','r',' ','-','D','O','P','E','N','S','S','L','_',
    'U','S','E','_','N','O','D','E','L','E','T','E',' ','-','D','O',
    'P','E','N','S','S','L','_','P','I','C',' ','-','D','_','_','A',
    'N','D','R','O','I','D','_','A','P','I','_','_','=','2','1',' ',
    '-','i','s','y','s','t','e','m',' ','/','o','p','t','/','a','n',
    'd','r','o','i','d','-','n','d','k','-','r','2','0','b','/','s',
    'y','s','r','o','o','t','/','u','s','r','/','i','n','c','l','u',
    'd','e','/','i','6','8','6','-','l','i','n','u','x','-','a','n',
    'd','r','o','i','d',' ','-','i','s','y','s','t','e','m',' ','/',
    'o','p','t','/','a','n','d','r','o','i','d','-','n','d','k','-',
    'r','2','0','b','/','s','y','s','r','o','o','t','/','u','s','r',
    '/','i','n','c','l','u','d','e',' ','-','D','N','D','E','B','U',
    'G',' ','-','D','_','_','A','N','D','R','O','I','D','_','A','P',
    'I','_','_','=','2','1','\0'
};
